function [fitresult, gof] = plot_error(anglevalues, errs, resultDir, isMu)
%CREATEFIT1(ANGLEVALUES,ERRS)
%  Create a fit.
%
%  Data for 'L2 error of gaussian fit' fit:
%      X Input : anglevalues
%      Y Output: errs
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Mar-2018 09:39:30


%% Fit: 'L2 error of gaussian fit'.
mu = cos(anglevalues)
[xData, yData] = prepareCurveData( anglevalues, errs );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
myFig = figure( 'Name', 'L2 error of Gaussian fit' );
h = plot( fitresult, xData, yData );
title('\fontsize{20} L2 Error of Gaussian Model');

% Label axes

if isMu
    xlabel ('\mu', 'FontSize', 20)
    legend( h, 'L2 Error Samples', 'Linear Interpolation of L2 error', 'Location', 'NorthEast' );
    filename = [resultDir, 'gaussian_error_mu'];
else
    xlabel ('\theta_i', 'FontSize', 20)
    legend( h, 'L2 Error Samples', 'Linear Interpolation of L2 error', 'Location', 'SouthEast' );
    filename = [resultDir, 'gaussian_error_theta'];
end
ylabel ('L2 error', 'FontSize', 20)
set(findall(myFig, 'Type', 'Text'),'FontWeight', 'Normal')

grid on
saveas(gcf,[filename,'.jpeg'])


